GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjQwNjE5ODksImV4cCI6MTcyNDA2MjAwNCwiYXVkIjoiNjZjMjgxZGE0YTAzNWMzYjc4ZDQ5ZDgyIiwiaXNzIjoiYXV0aG1lcm4uY29tIn0.pU_tbayswGKFiO4fkLpLH_kqkAiSC7JC_Q-xsqBpxcY

### Login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user@auth.com",
    "password": "12345"
}

### Profile route
GET http://localhost:3000/auth/profile

### Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "new@auth.com",
    "password": "12345"
}

### Refresh token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjQwOTgwMzQsImV4cCI6MTcyNDA5ODA2NCwiYXVkIjoiNjZjMjgxZGE0YTAzNWMzYjc4ZDQ5ZDgyIiwiaXNzIjoiYXV0aG1lcm4uY29tIn0.dCkL2dC0A2doaFNtJIe9_-iX7qmeBDdMynqft6_zxmk" 
}

### Logout route
DELETE http://localhost:3000/auth/logout