GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjQwNjE5ODksImV4cCI6MTcyNDA2MjAwNCwiYXVkIjoiNjZjMjgxZGE0YTAzNWMzYjc4ZDQ5ZDgyIiwiaXNzIjoiYXV0aG1lcm4uY29tIn0.pU_tbayswGKFiO4fkLpLH_kqkAiSC7JC_Q-xsqBpxcY

### Login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "user@auth.com",
    "password": "12345"
}

### Profile route
GET http://localhost:3000/auth/profile

### Register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "new@auth.com",
    "password": "12345"
}

### Refresh token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjQwNjUzMDEsImV4cCI6MTc1NTYyMjkwMSwiYXVkIjoiNjZjMjgxZGE0YTAzNWMzYjc4ZDQ5ZDgyIiwiaXNzIjoiYXV0aG1lcm4uY29tIn0.Oy_uhh6X7Dj5wFStideqpI16FYhQUwwW3u-TMa8jHFs" 
}

### Logout route
DELETE http://localhost:3000/auth/logout